### ISSUE TITLE
[BUG] Could not preload blitshader

### ISSUE THREAD

**Issue by egordorichev** [QuestCraftPlusPlus/QuestCraft#186]
Installed the questcraft using [this guide](https://www.youtube.com/watch?v=dh4_IRNCja4). Using fabric loader. Logged into my minecraft account using the switch account button.

The game crashes, in the crash log (sorry, no idea how to copy the whole thing) is the following error:

```
Could not preload blitshader
```

 - Device: Quest2
 - QuestCraft Version 1.1.1

Thanks for the amazing project!

**Comment by IzzyDotExe** [comment]
That single line isn't very helpful, please upload the full crash log.

**Comment by wellsilver** [comment]
You can use Pastebin to upload the full crash log and you can get it from your .minecraft
To get the crash log you can goto \.minecraft\crash-reports in sidequest

**Comment by egordorichev** [comment]
> You can use Pastebin to upload the full crash log (just ctrl+c and ctrl+v it into pastebin)
I'm very sorry for my little knowledge of the system, but how do you copy stuff on the headset without a bluetooth keyboard?

**Comment by wellsilver** [comment]
> I'm very sorry for my little knowledge of the system, but how do you copy stuff on the headset without a bluetooth keyboard?

To get the crash log you can goto .minecraft\crash-reports in sidequest

**Comment by egordorichev** [comment]
Here you go, [here is the full crash](https://pastebin.com/UGEHmsRb). Sorry for the mess.

```
Description: Initializing game

java.lang.RuntimeException: could not preload blit shader
	at net.minecraft.class_757.method_34521(class_757.java:404)
	at net.minecraft.class_310.<init>(class_310.java:617)
	at net.minecraft.client.main.Main.main(Main.java:199)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: net.minecraft.class_2973: Invalid shaders/core/blit_screen.json: Couldn't compile vertex program (minecraft:shaders/core/blit_screen.vsh, blit_screen) : No Shader support with current backend
	at net.minecraft.class_2973.method_12856(class_2973.java:48)
	at net.minecraft.class_5944.<init>(class_5944.java:200)
	at net.minecraft.class_757.method_34521(class_757.java:402)
	... 9 more
Caused by: java.io.IOException: Couldn't compile vertex program (minecraft:shaders/core/blit_screen.vsh, blit_screen) : No Shader support with current backend
	at net.minecraft.class_281.method_34416(class_281.java:72)
	at net.minecraft.class_281.method_1283(class_281.java:54)
	at net.minecraft.class_5944.method_34579(class_5944.java:241)
	at net.minecraft.class_5944.<init>(class_5944.java:182)
```

**Comment by IzzyDotExe** [comment]
Please make sure youre using the correct renderer

**Comment by egordorichev** [comment]
I tripple checked everything, tried every renderer,
this one is the third option called gles 1.1.5 exports opengl 2.1 + partial 3.2
