### ISSUE TITLE
[BUG] Attempt to invoke virtual method on a null object reference

### ISSUE THREAD

**Issue by vicentegaete5** [QuestCraftPlusPlus/QuestCraft#388]
After to install fabric loader for 1.18.2 or 1.19.2 and click play, the 3 dots apear for 1-3 minutes and crash. If I loggin again the launcher crash after 3 seconds aprox. or when i click play button and I receive Error message.

I really don't know what initiate the error. I had already installed questcraft in previous versions and had errors but I was able to solve them. does questcarft download data to some other folder besides android/data? I already uninstalled questcraft several ways but nothing worked so I suspect I didn't remove all the files from previous versions of questcraft.

I would like to know if there is any way to completely remove the questcraft files, or if uninstalling it directly is enough.

The Error message is: 

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String net.kdt.pojavlaunch.modmanager.State$Instance.getGameVersion()' on a null object reference
	at net.kdt.pojavlaunch.fragments.ModsFragment.loadDataIntoList(ModsFragment.java:91)
	at net.kdt.pojavlaunch.fragments.ModsFragment.access$000(ModsFragment.java:30)
	at net.kdt.pojavlaunch.fragments.ModsFragment$3.onItemSelected(ModsFragment.java:77)
	at android.widget.AdapterView.fireOnSelected(AdapterView.java:957)
	at android.widget.AdapterView.dispatchOnItemSelected(AdapterView.java:946)
	at android.widget.AdapterView.access$300(AdapterView.java:55)
	at android.widget.AdapterView$SelectionNotifier.run(AdapterView.java:910)
	at android.os.Handler.handleCallback(Handler.java:886)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7400)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

If you need more information I will leave everything like this until I have an answer

 - Quest Build: v43.0
 - Device: Quest 2
 - QuestCraft Version 2.0.1

One time I got the red screen and the music started but the start menu did not appear and when I hit the oculus button it returned to the launcher while the music was still playing in the background.

**Comment by Flopgop** [comment]
This is because minecraft is still open in the background, restart your quest and that'll fix it.
